/**
 * DCM 220 — Data Soal Lengkap
 * 220 pertanyaan dengan metadata bidang, sub bidang, tipe, dan arah jawaban
 */
const QUESTIONS_DATA = [
  { id:1, teks:"Saya sering merasa cemas tanpa alasan yang jelas akhir-akhir ini.", bidang:"Pribadi", sub_bidang:"Kesehatan Mental", tipe:"Core", arah:"Negative" },
  { id:2, teks:"Saya mudah terpancing emosi ketika melihat perdebatan di media sosial.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Negative" },
  { id:3, teks:"Saya bangga dan percaya diri dengan penampilan fisik saya saat ini.", bidang:"Pribadi", sub_bidang:"Consistency Pair 1", tipe:"Consistency Check", arah:"Positive", pair:1 },
  { id:4, teks:"Saya memiliki jadwal tidur yang teratur dan cukup istirahat.", bidang:"Pribadi", sub_bidang:"Consistency Pair 2", tipe:"Consistency Check", arah:"Positive", pair:2 },
  { id:5, teks:"Saya tidak pernah berbohong seumur hidup saya.", bidang:"Pribadi", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:6, teks:"Saya sering merasa lelah berkepanjangan meskipun tidak banyak beraktivitas.", bidang:"Pribadi", sub_bidang:"Kesehatan Fisik", tipe:"Core", arah:"Negative" },
  { id:7, teks:"Saya merasa kesulitan mengendalikan nafsu makan saat sedang stres.", bidang:"Pribadi", sub_bidang:"Kesehatan Fisik", tipe:"Core", arah:"Negative" },
  { id:8, teks:"Saya selalu meluangkan waktu untuk berolahraga ringan setiap minggu.", bidang:"Pribadi", sub_bidang:"Kesehatan Fisik", tipe:"Core", arah:"Positive" },
  { id:9, teks:"Saya sering mengorbankan waktu tidur demi bermain game atau menonton series.", bidang:"Pribadi", sub_bidang:"Gaya Hidup", tipe:"Core", arah:"Negative" },
  { id:10, teks:"Saya bisa menerima diri saya apa adanya tanpa harus selalu tampil sempurna.", bidang:"Pribadi", sub_bidang:"Kesehatan Mental", tipe:"Core", arah:"Positive" },
  { id:11, teks:"Saya sering overthinking memikirkan hal-hal yang belum terjadi.", bidang:"Pribadi", sub_bidang:"Kesehatan Mental", tipe:"Core", arah:"Negative" },
  { id:12, teks:"Saya merasa hidup saya kurang bermakna dibandingkan orang lain.", bidang:"Pribadi", sub_bidang:"Kesehatan Mental", tipe:"Core", arah:"Negative" },
  { id:13, teks:"Saya mampu menerima kritik dari orang lain dengan lapang dada.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Positive" },
  { id:14, teks:"Saya mudah menyerah saat menghadapi masalah yang rumit.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Negative" },
  { id:15, teks:"Saya selalu tersenyum bahagia setiap saat tanpa terkecuali.", bidang:"Pribadi", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:16, teks:"Saya merasa tenang saat berada jauh dari ponsel (HP) saya.", bidang:"Pribadi", sub_bidang:"Gaya Hidup", tipe:"Core", arah:"Positive" },
  { id:17, teks:"Saya memiliki kebiasaan menunda makan karena terlalu asyik dengan gadget.", bidang:"Pribadi", sub_bidang:"Kesehatan Fisik", tipe:"Core", arah:"Negative" },
  { id:18, teks:"Saya peduli pada kebersihan tubuh dan pakaian saya setiap hari.", bidang:"Pribadi", sub_bidang:"Kesehatan Fisik", tipe:"Core", arah:"Positive" },
  { id:19, teks:"Saya sering merasa pusing jika menatap layar terlalu lama.", bidang:"Pribadi", sub_bidang:"Kesehatan Fisik", tipe:"Core", arah:"Negative" },
  { id:20, teks:"Saya merasa kesulitan untuk memaafkan diri sendiri saat berbuat salah.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Negative" },
  { id:21, teks:"Saya sering merasa hampa atau kosong secara emosional.", bidang:"Pribadi", sub_bidang:"Kesehatan Mental", tipe:"Core", arah:"Negative" },
  { id:22, teks:"Saya bisa mengekspresikan kesedihan saya tanpa merasa lemah.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Positive" },
  { id:23, teks:"Saya meminum air putih dalam jumlah yang cukup setiap hari.", bidang:"Pribadi", sub_bidang:"Kesehatan Fisik", tipe:"Core", arah:"Positive" },
  { id:24, teks:"Saya sering mengalami sakit perut saat merasa tegang.", bidang:"Pribadi", sub_bidang:"Kesehatan Fisik", tipe:"Core", arah:"Negative" },
  { id:25, teks:"Saya tidak pernah membuang waktu luang saya sedetik pun.", bidang:"Pribadi", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:26, teks:"Saya merasa bentuk tubuh saya tidak ideal dan membuat saya malu.", bidang:"Pribadi", sub_bidang:"Consistency Pair 1", tipe:"Consistency Check", arah:"Negative", pair:1 },
  { id:27, teks:"Saya mudah merasa bersalah atas hal-hal yang bukan tanggung jawab saya.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Negative" },
  { id:28, teks:"Saya memiliki hobi yang membuat saya merasa rileks.", bidang:"Pribadi", sub_bidang:"Gaya Hidup", tipe:"Core", arah:"Positive" },
  { id:29, teks:"Saya sering mengonsumsi makanan instan/junk food lebih dari 3 kali seminggu.", bidang:"Pribadi", sub_bidang:"Kesehatan Fisik", tipe:"Core", arah:"Negative" },
  { id:30, teks:"Saya bisa membatasi pengeluaran uang saku agar tidak boros.", bidang:"Pribadi", sub_bidang:"Gaya Hidup", tipe:"Core", arah:"Positive" },
  { id:31, teks:"Saya sering begadang (doomscrolling) melihat TikTok/Reels sampai larut malam.", bidang:"Pribadi", sub_bidang:"Consistency Pair 2", tipe:"Consistency Check", arah:"Negative", pair:2 },
  { id:32, teks:"Saya tidak pernah iri melihat kesuksesan orang lain.", bidang:"Pribadi", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:33, teks:"Saya kesulitan mengatakan 'Tidak' pada permintaan yang memberatkan saya.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Negative" },
  { id:34, teks:"Saya merasa kesulitan beradaptasi dengan perubahan yang mendadak.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Negative" },
  { id:35, teks:"Saya rajin menjaga kebersihan kamar dan barang pribadi saya.", bidang:"Pribadi", sub_bidang:"Gaya Hidup", tipe:"Core", arah:"Positive" },
  { id:36, teks:"Saya merasa nyaman dan percaya diri dengan penampilan fisik saya di depan orang lain.", bidang:"Pribadi", sub_bidang:"Kesehatan Mental", tipe:"Core", arah:"Positive" },
  { id:37, teks:"Saya tahu cara menenangkan diri sendiri saat sedang panik.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Positive" },
  { id:38, teks:"Saya merasa spiritualitas/ibadah membantu menenangkan pikiran saya.", bidang:"Pribadi", sub_bidang:"Nilai & Moral", tipe:"Core", arah:"Positive" },
  { id:39, teks:"Saya merasa aturan agama terlalu mengekang kebebasan saya.", bidang:"Pribadi", sub_bidang:"Nilai & Moral", tipe:"Core", arah:"Negative" },
  { id:40, teks:"Saya tidak mudah terpengaruh oleh tren yang bertentangan dengan prinsip saya.", bidang:"Pribadi", sub_bidang:"Nilai & Moral", tipe:"Core", arah:"Positive" },
  { id:41, teks:"Saya sering berbohong kecil untuk menghindari masalah.", bidang:"Pribadi", sub_bidang:"Nilai & Moral", tipe:"Core", arah:"Negative" },
  { id:42, teks:"Saya selalu mematuhi semua aturan sekolah tanpa pernah melanggar sedikit pun.", bidang:"Pribadi", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:43, teks:"Saya merasa tidak memiliki tujuan hidup yang jelas saat ini.", bidang:"Pribadi", sub_bidang:"Kesehatan Mental", tipe:"Core", arah:"Negative" },
  { id:44, teks:"Saya cepat merasa bosan dengan rutinitas harian saya.", bidang:"Pribadi", sub_bidang:"Gaya Hidup", tipe:"Core", arah:"Negative" },
  { id:45, teks:"Saya selalu merencanakan hal-hal yang akan saya lakukan besok.", bidang:"Pribadi", sub_bidang:"Gaya Hidup", tipe:"Core", arah:"Positive" },
  { id:46, teks:"Saya peduli terhadap dampak lingkungan dari gaya hidup saya.", bidang:"Pribadi", sub_bidang:"Nilai & Moral", tipe:"Core", arah:"Positive" },
  { id:47, teks:"Saya merasa sulit mempercayai orang lain sepenuhnya.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Negative" },
  { id:48, teks:"Saya tidak malu meminta bantuan profesional jika mental saya sedang down.", bidang:"Pribadi", sub_bidang:"Kesehatan Mental", tipe:"Core", arah:"Positive" },
  { id:49, teks:"Saya sering meragukan kemampuan diri saya sendiri (imposter syndrome).", bidang:"Pribadi", sub_bidang:"Kesehatan Mental", tipe:"Core", arah:"Negative" },
  { id:50, teks:"Saya selalu berusaha mencari sisi positif dari sebuah kegagalan.", bidang:"Pribadi", sub_bidang:"Kematangan Emosi", tipe:"Core", arah:"Positive" },
  { id:51, teks:"Saya tidak pernah marah ketika dihina oleh siapa pun.", bidang:"Pribadi", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:52, teks:"Saya sering menggunakan AI (seperti ChatGPT) sekadar copy-paste tanpa dipahami.", bidang:"Belajar", sub_bidang:"Consistency Pair 3", tipe:"Consistency Check", arah:"Negative", pair:3 },
  { id:53, teks:"Semangat belajar saya tetap tinggi dalam kondisi apa pun.", bidang:"Belajar", sub_bidang:"Consistency Pair 4", tipe:"Consistency Check", arah:"Positive", pair:4 },
  { id:54, teks:"Saya merasa pelajaran di sekolah tidak relevan dengan dunia nyata saat ini.", bidang:"Belajar", sub_bidang:"Motivasi Belajar", tipe:"Core", arah:"Negative" },
  { id:55, teks:"Saya bisa mengatur waktu antara belajar dan bermain dengan seimbang.", bidang:"Belajar", sub_bidang:"Manajemen Waktu", tipe:"Core", arah:"Positive" },
  { id:56, teks:"Saya sering menunda mengerjakan tugas (prokrastinasi) hingga mendekati deadline.", bidang:"Belajar", sub_bidang:"Manajemen Waktu", tipe:"Core", arah:"Negative" },
  { id:57, teks:"Saya kesulitan fokus belajar karena sering terganggu notifikasi HP.", bidang:"Belajar", sub_bidang:"Fokus Belajar", tipe:"Core", arah:"Negative" },
  { id:58, teks:"Saya memiliki metode belajar sendiri yang efektif untuk saya.", bidang:"Belajar", sub_bidang:"Keterampilan Belajar", tipe:"Core", arah:"Positive" },
  { id:59, teks:"Saya merasa tugas sekolah saat ini terlalu banyak dan menguras energi.", bidang:"Belajar", sub_bidang:"Beban Belajar", tipe:"Core", arah:"Negative" },
  { id:60, teks:"Saya berani bertanya kepada guru jika ada materi yang tidak dipahami.", bidang:"Belajar", sub_bidang:"Sikap Belajar", tipe:"Core", arah:"Positive" },
  { id:61, teks:"Saya tidak pernah merasa malas untuk belajar.", bidang:"Belajar", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:62, teks:"Saya sering merasa mengantuk berat saat jam pelajaran berlangsung.", bidang:"Belajar", sub_bidang:"Fokus Belajar", tipe:"Core", arah:"Negative" },
  { id:63, teks:"Saya merasa metode mengajar sebagian guru sangat membosankan.", bidang:"Belajar", sub_bidang:"Lingkungan Sekolah", tipe:"Core", arah:"Negative" },
  { id:64, teks:"Saya menggunakan internet dan YouTube untuk memperdalam materi sekolah.", bidang:"Belajar", sub_bidang:"Keterampilan Belajar", tipe:"Core", arah:"Positive" },
  { id:65, teks:"Saya merasa tekanan untuk mendapat nilai tinggi membuat saya stres.", bidang:"Belajar", sub_bidang:"Beban Belajar", tipe:"Core", arah:"Negative" },
  { id:66, teks:"Saya sering ikut-ikutan teman saat bolos atau tidak mengerjakan PR.", bidang:"Belajar", sub_bidang:"Sikap Belajar", tipe:"Core", arah:"Negative" },
  { id:67, teks:"Saya merasa ruang kelas saya nyaman dan mendukung proses belajar.", bidang:"Belajar", sub_bidang:"Lingkungan Sekolah", tipe:"Core", arah:"Positive" },
  { id:68, teks:"Saya kehilangan konsentrasi jika suasana belajar terlalu berisik.", bidang:"Belajar", sub_bidang:"Fokus Belajar", tipe:"Core", arah:"Negative" },
  { id:69, teks:"Saya selalu mengerjakan tugas sendiri sebelum menggunakan bantuan AI.", bidang:"Belajar", sub_bidang:"Consistency Pair 3", tipe:"Consistency Check", arah:"Positive", pair:3 },
  { id:70, teks:"Saya merasa sangat malas memulai belajar setelah libur panjang.", bidang:"Belajar", sub_bidang:"Motivasi Belajar", tipe:"Core", arah:"Negative" },
  { id:71, teks:"Saya selalu mendengarkan penjelasan guru dengan penuh perhatian penuh.", bidang:"Belajar", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:72, teks:"Saya memiliki target nilai yang realistis dan berusaha mencapainya.", bidang:"Belajar", sub_bidang:"Motivasi Belajar", tipe:"Core", arah:"Positive" },
  { id:73, teks:"Saya merasa kesulitan memahami materi eksakta (seperti Matematika/Fisika).", bidang:"Belajar", sub_bidang:"Keterampilan Belajar", tipe:"Core", arah:"Negative" },
  { id:74, teks:"Saya lebih mudah belajar dengan menonton video daripada membaca buku teks.", bidang:"Belajar", sub_bidang:"Keterampilan Belajar", tipe:"Core", arah:"Positive" },
  { id:75, teks:"Saya merasa buku perpustakaan sekolah kurang update dan kurang lengkap.", bidang:"Belajar", sub_bidang:"Fasilitas Belajar", tipe:"Core", arah:"Negative" },
  { id:76, teks:"Saya rajin membuat catatan atau mind map agar lebih mudah mengingat materi.", bidang:"Belajar", sub_bidang:"Keterampilan Belajar", tipe:"Core", arah:"Positive" },
  { id:77, teks:"Saya sering lupa materi pelajaran sesaat setelah ujian selesai.", bidang:"Belajar", sub_bidang:"Keterampilan Belajar", tipe:"Core", arah:"Negative" },
  { id:78, teks:"Saya belajar hanya saat besok akan diadakan ujian (Sistem SKS).", bidang:"Belajar", sub_bidang:"Manajemen Waktu", tipe:"Core", arah:"Negative" },
  { id:79, teks:"Saya merasa sekolah tidak memberikan ruang untuk mengembangkan kreativitas.", bidang:"Belajar", sub_bidang:"Lingkungan Sekolah", tipe:"Core", arah:"Negative" },
  { id:80, teks:"Saya mampu mencari jalan keluar saat kesulitan mengerjakan tugas yang sulit.", bidang:"Belajar", sub_bidang:"Sikap Belajar", tipe:"Core", arah:"Positive" },
  { id:81, teks:"Saya tidak pernah sekalipun menyontek saat ujian.", bidang:"Belajar", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:82, teks:"Saya kehilangan motivasi belajar semenjak terbiasa dengan sekolah online/pandemi.", bidang:"Belajar", sub_bidang:"Consistency Pair 4", tipe:"Consistency Check", arah:"Negative", pair:4 },
  { id:83, teks:"Saya merasa fasilitas lab/komputer di sekolah sangat tertinggal.", bidang:"Belajar", sub_bidang:"Fasilitas Belajar", tipe:"Core", arah:"Negative" },
  { id:84, teks:"Saya tergabung dalam kelompok belajar yang saling mendukung.", bidang:"Belajar", sub_bidang:"Lingkungan Sosial Belajar", tipe:"Core", arah:"Positive" },
  { id:85, teks:"Saya merasa enggan belajar kelompok karena ujung-ujungnya hanya mengobrol.", bidang:"Belajar", sub_bidang:"Lingkungan Sosial Belajar", tipe:"Core", arah:"Negative" },
  { id:86, teks:"Saya merasa guru memiliki anak emas (favorit) di kelas.", bidang:"Belajar", sub_bidang:"Lingkungan Sekolah", tipe:"Core", arah:"Negative" },
  { id:87, teks:"Saya bersemangat saat diberikan tugas yang berbasis proyek nyata.", bidang:"Belajar", sub_bidang:"Motivasi Belajar", tipe:"Core", arah:"Positive" },
  { id:88, teks:"Saya merasa kesulitan menyampaikan pendapat saat diskusi kelas.", bidang:"Belajar", sub_bidang:"Sikap Belajar", tipe:"Core", arah:"Negative" },
  { id:89, teks:"Saya mencatat jadwal ujian dan pengumpulan tugas dengan rapi.", bidang:"Belajar", sub_bidang:"Manajemen Waktu", tipe:"Core", arah:"Positive" },
  { id:90, teks:"Saya merasa sistem pendidikan saat ini hanya mementingkan nilai angka.", bidang:"Belajar", sub_bidang:"Motivasi Belajar", tipe:"Core", arah:"Negative" },
  { id:91, teks:"Saya selalu memaafkan teman yang menyakiti saya saat itu juga.", bidang:"Sosial", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:92, teks:"Saya khawatir akan gagal lulus dengan nilai yang memuaskan.", bidang:"Belajar", sub_bidang:"Beban Belajar", tipe:"Core", arah:"Negative" },
  { id:93, teks:"Saya merasa ada mata pelajaran yang sama sekali tidak ada gunanya bagi saya.", bidang:"Belajar", sub_bidang:"Motivasi Belajar", tipe:"Core", arah:"Negative" },
  { id:94, teks:"Saya rutin membaca buku atau artikel di luar materi wajib sekolah.", bidang:"Belajar", sub_bidang:"Keterampilan Belajar", tipe:"Core", arah:"Positive" },
  { id:95, teks:"Saya merasa kelelahan karena harus mengikuti banyak les tambahan/bimbel.", bidang:"Belajar", sub_bidang:"Beban Belajar", tipe:"Core", arah:"Negative" },
  { id:96, teks:"Saya merasa tertinggal materi dibandingkan teman-teman sekelas.", bidang:"Belajar", sub_bidang:"Beban Belajar", tipe:"Core", arah:"Negative" },
  { id:97, teks:"Saya selalu mengecek ulang lembar jawaban saya sebelum dikumpulkan.", bidang:"Belajar", sub_bidang:"Sikap Belajar", tipe:"Core", arah:"Positive" },
  { id:98, teks:"Saya mudah panik saat tiba-tiba diadakan kuis dadakan.", bidang:"Belajar", sub_bidang:"Fokus Belajar", tipe:"Core", arah:"Negative" },
  { id:99, teks:"Saya memiliki tempat belajar yang khusus dan nyaman di rumah.", bidang:"Belajar", sub_bidang:"Fasilitas Belajar", tipe:"Core", arah:"Positive" },
  { id:100, teks:"Saya sering merasa mengerti saat guru menjelaskan tapi bingung saat mengerjakan soal.", bidang:"Belajar", sub_bidang:"Keterampilan Belajar", tipe:"Core", arah:"Negative" },
  { id:101, teks:"Saya tidak pernah membicarakan keburukan orang lain di belakangnya.", bidang:"Sosial", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:102, teks:"Saya merasa prestasi saya menurun di semester terakhir ini.", bidang:"Belajar", sub_bidang:"Motivasi Belajar", tipe:"Core", arah:"Negative" },
  { id:103, teks:"Saya berusaha mematuhi tata tertib sekolah meskipun tidak ada guru.", bidang:"Belajar", sub_bidang:"Sikap Belajar", tipe:"Core", arah:"Positive" },
  { id:104, teks:"Saya lebih suka belajar secara mandiri daripada berkelompok.", bidang:"Belajar", sub_bidang:"Lingkungan Sosial Belajar", tipe:"Core", arah:"Positive" },
  { id:105, teks:"Saya sering lupa membawa buku atau perlengkapan sekolah yang dibutuhkan.", bidang:"Belajar", sub_bidang:"Manajemen Waktu", tipe:"Core", arah:"Negative" },
  { id:106, teks:"Saya memiliki target universitas yang memacu saya belajar lebih keras.", bidang:"Belajar", sub_bidang:"Motivasi Belajar", tipe:"Core", arah:"Positive" },
  { id:107, teks:"Saya merasa cemas jika ketinggalan tren terbaru di media sosial (FOMO).", bidang:"Sosial", sub_bidang:"Consistency Pair 5", tipe:"Consistency Check", arah:"Negative", pair:5 },
  { id:108, teks:"Saya merasa terjebak dalam lingkungan pertemanan yang toxic.", bidang:"Sosial", sub_bidang:"Consistency Pair 6", tipe:"Consistency Check", arah:"Negative", pair:6 },
  { id:109, teks:"Saya merasa orang tua terlalu memaksakan kehendak mereka pada saya.", bidang:"Sosial", sub_bidang:"Consistency Pair 7", tipe:"Consistency Check", arah:"Negative", pair:7 },
  { id:110, teks:"Saya memiliki sahabat yang bisa dipercaya menjaga rahasia saya.", bidang:"Sosial", sub_bidang:"Hubungan Teman", tipe:"Core", arah:"Positive" },
  { id:111, teks:"Saya tidak pernah merasa malas untuk menolong orang yang tidak saya kenal.", bidang:"Sosial", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:112, teks:"Saya merasa energi saya cepat habis setelah berinteraksi dengan banyak orang (Social Battery).", bidang:"Sosial", sub_bidang:"Hubungan Teman", tipe:"Core", arah:"Negative" },
  { id:113, teks:"Saya kesulitan memulai obrolan dengan orang yang baru dikenal.", bidang:"Sosial", sub_bidang:"Keterampilan Sosial", tipe:"Core", arah:"Negative" },
  { id:114, teks:"Saya mampu menempatkan diri dan bersikap sopan pada orang yang lebih tua.", bidang:"Sosial", sub_bidang:"Etika Sosial", tipe:"Core", arah:"Positive" },
  { id:115, teks:"Saya pernah menjadi korban perundungan (bullying) secara verbal maupun fisik.", bidang:"Sosial", sub_bidang:"Masalah Sosial", tipe:"Core", arah:"Negative" },
  { id:116, teks:"Saya aktif mengikuti kegiatan ekstrakurikuler atau organisasi di sekolah.", bidang:"Sosial", sub_bidang:"Gaya Hidup & Lingkungan Sosial", tipe:"Core", arah:"Positive" },
  { id:117, teks:"Saya merasa dikucilkan jika tidak mengikuti apa yang teman-teman lakukan.", bidang:"Sosial", sub_bidang:"Masalah Sosial", tipe:"Core", arah:"Negative" },
  { id:118, teks:"Saya berani menegur teman yang melakukan perbuatan salah/melanggar aturan.", bidang:"Sosial", sub_bidang:"Keterampilan Sosial", tipe:"Core", arah:"Positive" },
  { id:119, teks:"Saya menyempatkan waktu untuk ngobrol langsung dengan keluarga setiap harinya.", bidang:"Sosial", sub_bidang:"Hubungan Keluarga", tipe:"Core", arah:"Positive" },
  { id:120, teks:"Saya selalu setuju dengan nasihat orang tua tanpa pernah membantah sekalipun.", bidang:"Sosial", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:121, teks:"Saya merasa tenang dan tidak peduli meskipun tidak mengikuti hal yang sedang viral.", bidang:"Sosial", sub_bidang:"Consistency Pair 5", tipe:"Consistency Check", arah:"Positive", pair:5 },
  { id:122, teks:"Saya pernah melakukan cyberbullying atau menulis komentar jahat tanpa sadar.", bidang:"Sosial", sub_bidang:"Masalah Sosial", tipe:"Core", arah:"Negative" },
  { id:123, teks:"Saya menghindari konflik terbuka dan lebih memilih diam jika marah pada teman.", bidang:"Sosial", sub_bidang:"Keterampilan Sosial", tipe:"Core", arah:"Negative" },
  { id:124, teks:"Saya merasa rumah bukanlah tempat yang nyaman untuk beristirahat.", bidang:"Sosial", sub_bidang:"Hubungan Keluarga", tipe:"Core", arah:"Negative" },
  { id:125, teks:"Teman-teman terdekat saya selalu mendukung perkembangan positif saya.", bidang:"Sosial", sub_bidang:"Consistency Pair 6", tipe:"Consistency Check", arah:"Positive", pair:6 },
  { id:126, teks:"Saya mudah merasa simpati ketika melihat orang lain tertimpa musibah.", bidang:"Sosial", sub_bidang:"Keterampilan Sosial", tipe:"Core", arah:"Positive" },
  { id:127, teks:"Saya memiliki akun alter/second account untuk menyembunyikan identitas asli saya.", bidang:"Sosial", sub_bidang:"Gaya Hidup & Lingkungan Sosial", tipe:"Core", arah:"Negative" },
  { id:128, teks:"Saya dan orang tua punya waktu berkualitas bersama meski di tengah kesibukan.", bidang:"Sosial", sub_bidang:"Hubungan Keluarga", tipe:"Core", arah:"Positive" },
  { id:129, teks:"Saya tahu etika yang baik saat berinteraksi di media sosial.", bidang:"Sosial", sub_bidang:"Etika Sosial", tipe:"Core", arah:"Positive" },
  { id:130, teks:"Saya tidak pernah sekalipun merasa kesal pada orang tua.", bidang:"Sosial", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:131, teks:"Orang tua saya memberikan kebebasan bagi saya untuk memilih jalan hidup sendiri.", bidang:"Sosial", sub_bidang:"Consistency Pair 7", tipe:"Consistency Check", arah:"Positive", pair:7 },
  { id:132, teks:"Saya memiliki batasan yang jelas dalam bergaul dengan lawan jenis.", bidang:"Sosial", sub_bidang:"Etika Sosial", tipe:"Core", arah:"Positive" },
  { id:133, teks:"Saya mampu menolak ajakan teman yang tidak sesuai dengan nilai dan prinsip saya.", bidang:"Sosial", sub_bidang:"Masalah Sosial", tipe:"Core", arah:"Positive" },
  { id:134, teks:"Saya bisa menghargai pendapat orang lain walau sangat bertentangan dengan saya.", bidang:"Sosial", sub_bidang:"Keterampilan Sosial", tipe:"Core", arah:"Positive" },
  { id:135, teks:"Saya merasa cemas memikirkan kehidupan asmara/percintaan saya saat ini.", bidang:"Sosial", sub_bidang:"Masalah Sosial", tipe:"Core", arah:"Negative" },
  { id:136, teks:"Saya merasa keluarga saya sering ribut karena masalah finansial.", bidang:"Sosial", sub_bidang:"Hubungan Keluarga", tipe:"Core", arah:"Negative" },
  { id:137, teks:"Saya sering mengabaikan kebersihan dan ketertiban fasilitas umum di sekitar saya.", bidang:"Sosial", sub_bidang:"Etika Sosial", tipe:"Core", arah:"Negative" },
  { id:138, teks:"Saya menjaga keseimbangan antara interaksi sosial online dan pertemuan langsung dengan teman.", bidang:"Sosial", sub_bidang:"Masalah Sosial", tipe:"Core", arah:"Positive" },
  { id:139, teks:"Saya selalu menyukai semua teman sekelas tanpa terkecuali.", bidang:"Sosial", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:140, teks:"Saya berani menolak ajakan teman jika itu merugikan masa depan saya.", bidang:"Sosial", sub_bidang:"Keterampilan Sosial", tipe:"Core", arah:"Positive" },
  { id:141, teks:"Saya pernah merasa ingin membalas dendam pada orang yang menyakiti saya.", bidang:"Sosial", sub_bidang:"Keterampilan Sosial", tipe:"Core", arah:"Negative" },
  { id:142, teks:"Orang tua saya sering membanding-bandingkan saya dengan anak orang lain.", bidang:"Sosial", sub_bidang:"Hubungan Keluarga", tipe:"Core", arah:"Negative" },
  { id:143, teks:"Saya kadang melanggar aturan sosial jika tidak ada orang yang mengawasi saya.", bidang:"Sosial", sub_bidang:"Etika Sosial", tipe:"Core", arah:"Negative" },
  { id:144, teks:"Saya sering merasa canggung saat berada di acara kumpul keluarga besar.", bidang:"Sosial", sub_bidang:"Keterampilan Sosial", tipe:"Core", arah:"Negative" },
  { id:145, teks:"Saya memiliki seseorang di keluarga yang selalu mendengarkan keluh kesah saya.", bidang:"Sosial", sub_bidang:"Hubungan Keluarga", tipe:"Core", arah:"Positive" },
  { id:146, teks:"Saya menjauhi lingkungan pergaulan yang menggunakan obat terlarang atau alkohol.", bidang:"Sosial", sub_bidang:"Masalah Sosial", tipe:"Core", arah:"Positive" },
  { id:147, teks:"Saya sering ikut menghakimi (cancel culture) seseorang di internet tanpa tahu fakta aslinya.", bidang:"Sosial", sub_bidang:"Masalah Sosial", tipe:"Core", arah:"Negative" },
  { id:148, teks:"Saya tidak pernah mengeluh meski diberi tugas yang sangat berat.", bidang:"Sosial", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:149, teks:"Saya menghormati perbedaan agama dan suku dalam pergaulan sehari-hari.", bidang:"Sosial", sub_bidang:"Etika Sosial", tipe:"Core", arah:"Positive" },
  { id:150, teks:"Saya pernah merasa trauma akibat konflik berat di dalam keluarga (broken home).", bidang:"Sosial", sub_bidang:"Hubungan Keluarga", tipe:"Core", arah:"Negative" },
  { id:151, teks:"Saya merasa bangga ketika bisa membantu menyelesaikan masalah teman.", bidang:"Sosial", sub_bidang:"Keterampilan Sosial", tipe:"Core", arah:"Positive" },
  { id:152, teks:"Saya sering menyembunyikan masalah dari orang tua agar mereka tidak kepikiran.", bidang:"Sosial", sub_bidang:"Hubungan Keluarga", tipe:"Core", arah:"Negative" },
  { id:153, teks:"Saya merasa persaingan antar teman di sekolah sangat tidak sehat.", bidang:"Sosial", sub_bidang:"Hubungan Teman", tipe:"Core", arah:"Negative" },
  { id:154, teks:"Saya masih sangat kebingungan menentukan jurusan kuliah atau pekerjaan impian.", bidang:"Karir", sub_bidang:"Consistency Pair 8", tipe:"Consistency Check", arah:"Negative", pair:8 },
  { id:155, teks:"Saya khawatir kondisi ekonomi keluarga akan menghambat cita-cita saya.", bidang:"Karir", sub_bidang:"Consistency Pair 9", tipe:"Consistency Check", arah:"Negative", pair:9 },
  { id:156, teks:"Saya tahu apa saja kekuatan dan kelemahan terbesar dalam diri saya.", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Positive" },
  { id:157, teks:"Saya selalu paham semua materi pelajaran sejak pertama kali diajarkan.", bidang:"Karir", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:158, teks:"Saya sering merasa pesimis membayangkan sulitnya mencari pekerjaan di masa depan.", bidang:"Karir", sub_bidang:"Kesiapan Karir", tipe:"Core", arah:"Negative" },
  { id:159, teks:"Saya sudah mencari informasi detail tentang kampus atau jurusan yang saya tuju.", bidang:"Karir", sub_bidang:"Perencanaan Karir", tipe:"Core", arah:"Positive" },
  { id:160, teks:"Saya merasa bakat yang saya miliki tidak dihargai di lingkungan sekolah.", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Negative" },
  { id:161, teks:"Saya takut profesi yang saya impikan akan tergantikan oleh Artificial Intelligence (AI).", bidang:"Karir", sub_bidang:"Kesiapan Karir", tipe:"Core", arah:"Negative" },
  { id:162, teks:"Saya merasa jurusan yang saya inginkan bertentangan dengan kemauan orang tua.", bidang:"Karir", sub_bidang:"Perencanaan Karir", tipe:"Core", arah:"Negative" },
  { id:163, teks:"Saya merasa belum memiliki skill khusus yang bisa dibanggakan untuk dunia kerja.", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Negative" },
  { id:164, teks:"Saya merasa gengsi jika nanti harus bekerja di bidang yang gajinya kecil.", bidang:"Karir", sub_bidang:"Kesiapan Karir", tipe:"Core", arah:"Negative" },
  { id:165, teks:"Saya tidak pernah menyontek ide orang lain seumur hidup saya.", bidang:"Karir", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:166, teks:"Saya sudah memiliki rencana karir atau studi lanjut yang sangat jelas.", bidang:"Karir", sub_bidang:"Consistency Pair 8", tipe:"Consistency Check", arah:"Positive", pair:8 },
  { id:167, teks:"Saya tahu cara membuat riwayat hidup (CV) yang baik dan benar.", bidang:"Karir", sub_bidang:"Keterampilan Praktis", tipe:"Core", arah:"Positive" },
  { id:168, teks:"Saya yakin kondisi finansial keluarga mampu mendukung penuh pendidikan lanjutan saya.", bidang:"Karir", sub_bidang:"Consistency Pair 9", tipe:"Consistency Check", arah:"Positive", pair:9 },
  { id:169, teks:"Saya menyadari pentingnya belajar bahasa asing untuk karir masa depan.", bidang:"Karir", sub_bidang:"Keterampilan Praktis", tipe:"Core", arah:"Positive" },
  { id:170, teks:"Saya sering membayangkan diri saya sukses memimpin sebuah perusahaan atau proyek.", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Positive" },
  { id:171, teks:"Saya ragu apakah saya sanggup hidup mandiri jauh dari orang tua saat kuliah/kerja nanti.", bidang:"Karir", sub_bidang:"Kesiapan Karir", tipe:"Core", arah:"Negative" },
  { id:172, teks:"Saya selalu bekerja maksimal tanpa mengharapkan imbalan apa pun.", bidang:"Karir", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:173, teks:"Saya memanfaatkan media sosial untuk membangun personal branding yang positif.", bidang:"Karir", sub_bidang:"Keterampilan Praktis", tipe:"Core", arah:"Positive" },
  { id:174, teks:"Saya memiliki idola atau role model profesional yang menginspirasi karir saya.", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Positive" },
  { id:175, teks:"Saya sering mengubah-ubah pilihan cita-cita setiap kali melihat tren baru.", bidang:"Karir", sub_bidang:"Perencanaan Karir", tipe:"Core", arah:"Negative" },
  { id:176, teks:"Saya sudah mempersiapkan mental untuk menghadapi penolakan (kegagalan) di masa depan.", bidang:"Karir", sub_bidang:"Kesiapan Karir", tipe:"Core", arah:"Positive" },
  { id:177, teks:"Saya memilih jurusan berdasarkan minat dan passion, bukan sekadar gaji yang tinggi.", bidang:"Karir", sub_bidang:"Perencanaan Karir", tipe:"Core", arah:"Positive" },
  { id:178, teks:"Saya merasa tidak memiliki satu pun mata pelajaran yang menonjol.", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Negative" },
  { id:179, teks:"Saya bersedia keluar dari zona nyaman demi mengejar karir impian.", bidang:"Karir", sub_bidang:"Kesiapan Karir", tipe:"Core", arah:"Positive" },
  { id:180, teks:"Saya tidak pernah menyesali satupun keputusan yang saya ambil.", bidang:"Karir", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:181, teks:"Saya rajin mengasah keterampilan komunikasi (public speaking) untuk modal kerja.", bidang:"Karir", sub_bidang:"Keterampilan Praktis", tipe:"Core", arah:"Positive" },
  { id:182, teks:"Saya terbuka untuk mempelajari bidang baru yang sama sekali tidak saya kuasai.", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Positive" },
  { id:183, teks:"Saya tahu cara mencari informasi beasiswa secara mandiri di internet.", bidang:"Karir", sub_bidang:"Keterampilan Praktis", tipe:"Core", arah:"Positive" },
  { id:184, teks:"Saya merasa kemampuan dasar komputer (seperti Excel/Word) saya masih sangat kurang.", bidang:"Karir", sub_bidang:"Keterampilan Praktis", tipe:"Core", arah:"Negative" },
  { id:185, teks:"Saya memiliki keinginan kuat untuk bisa membuka lapangan pekerjaan (wirausaha).", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Positive" },
  { id:186, teks:"Saya pesimis bisa masuk ke perguruan tinggi negeri impian melalui jalur tes.", bidang:"Karir", sub_bidang:"Perencanaan Karir", tipe:"Core", arah:"Negative" },
  { id:187, teks:"Saya tidak pernah menangis atau merasa sedih karena urusan masa depan.", bidang:"Karir", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:188, teks:"Saya merasa belum siap dan gugup jika harus menghadapi sesi wawancara kerja sekarang.", bidang:"Karir", sub_bidang:"Keterampilan Praktis", tipe:"Core", arah:"Negative" },
  { id:189, teks:"Saya belum memahami konsep dasar mengelola uang dan berinvestasi untuk masa depan.", bidang:"Karir", sub_bidang:"Keterampilan Praktis", tipe:"Core", arah:"Negative" },
  { id:190, teks:"Saya takut salah pilih jurusan dan menyesal di kemudian hari.", bidang:"Karir", sub_bidang:"Perencanaan Karir", tipe:"Core", arah:"Negative" },
  { id:191, teks:"Saya sudah mempersiapkan portofolio atau bukti karya dari hobi yang saya tekuni.", bidang:"Karir", sub_bidang:"Keterampilan Praktis", tipe:"Core", arah:"Positive" },
  { id:192, teks:"Saya memiliki jiwa kepemimpinan dan suka memimpin kelompok.", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Positive" },
  { id:193, teks:"Saya aktif mencari informasi kampus, jurusan, dan karir secara mandiri tanpa menunggu.", bidang:"Karir", sub_bidang:"Perencanaan Karir", tipe:"Core", arah:"Positive" },
  { id:194, teks:"Saya merasa jurusan SMA/SMK saya saat ini tidak sesuai dengan bakat saya.", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Negative" },
  { id:195, teks:"Saya yakin bisa sukses berkarir meskipun tidak berkuliah.", bidang:"Karir", sub_bidang:"Kesiapan Karir", tipe:"Core", arah:"Positive" },
  { id:196, teks:"Saya tidak pernah ragu sedetik pun akan kehebatan diri saya.", bidang:"Karir", sub_bidang:"Lie Scale", tipe:"Lie Scale", arah:"Positive" },
  { id:197, teks:"Saya merasa bingung membedakan antara hobi sesaat dan passion sejati untuk berkarir.", bidang:"Karir", sub_bidang:"Minat & Bakat", tipe:"Core", arah:"Negative" },
  { id:198, teks:"Saya sering ikut-ikutan teman melakukan hal yang sebenarnya tidak saya sukai.", bidang:"Sosial", sub_bidang:"Gaya Hidup & Lingkungan Sosial", tipe:"Core", arah:"Negative" },
  { id:199, teks:"Saya merasa cemas ketika teman-teman jalan bareng tapi saya tidak diajak (FOMO).", bidang:"Sosial", sub_bidang:"Gaya Hidup & Lingkungan Sosial", tipe:"Core", arah:"Negative" },
  { id:200, teks:"Saya lebih memilih menghabiskan waktu luang sendiri daripada berkumpul dengan teman.", bidang:"Sosial", sub_bidang:"Gaya Hidup & Lingkungan Sosial", tipe:"Core", arah:"Negative" },
  { id:201, teks:"Saya merasa nyaman dan diterima di lingkungan pertemanan saya saat ini.", bidang:"Sosial", sub_bidang:"Gaya Hidup & Lingkungan Sosial", tipe:"Core", arah:"Positive" },
  { id:202, teks:"Saya bisa memilih pergaulan yang baik tanpa terpengaruh tekanan lingkungan sekitar.", bidang:"Sosial", sub_bidang:"Gaya Hidup & Lingkungan Sosial", tipe:"Core", arah:"Positive" },
  { id:203, teks:"Saya aktif terlibat dalam kegiatan di lingkungan rumah atau komunitas sekitar.", bidang:"Sosial", sub_bidang:"Gaya Hidup & Lingkungan Sosial", tipe:"Core", arah:"Positive" },
  { id:204, teks:"Saya kesulitan mengakses internet yang stabil untuk keperluan belajar di rumah.", bidang:"Belajar", sub_bidang:"Fasilitas Belajar", tipe:"Core", arah:"Negative" },
  { id:205, teks:"Saya sering kekurangan alat tulis atau buku karena keterbatasan ekonomi.", bidang:"Belajar", sub_bidang:"Fasilitas Belajar", tipe:"Core", arah:"Negative" },
  { id:206, teks:"Saya memiliki akses ke perangkat (laptop/tablet) yang mendukung kegiatan belajar saya.", bidang:"Belajar", sub_bidang:"Fasilitas Belajar", tipe:"Core", arah:"Positive" },
  { id:207, teks:"Saya merasa teman sekelas justru sering mengalihkan fokus saat belajar bersama.", bidang:"Belajar", sub_bidang:"Lingkungan Sosial Belajar", tipe:"Core", arah:"Negative" },
  { id:208, teks:"Saya canggung meminta tolong ke teman untuk menjelaskan ulang materi yang tidak dipahami.", bidang:"Belajar", sub_bidang:"Lingkungan Sosial Belajar", tipe:"Core", arah:"Negative" },
  { id:209, teks:"Saya senang berdiskusi dengan teman karena bisa saling melengkapi pemahaman materi.", bidang:"Belajar", sub_bidang:"Lingkungan Sosial Belajar", tipe:"Core", arah:"Positive" },
  { id:210, teks:"Saya merasa teman-teman tidak terlalu peduli dengan masalah yang saya hadapi.", bidang:"Sosial", sub_bidang:"Hubungan Teman", tipe:"Core", arah:"Negative" },
  { id:211, teks:"Saya mudah tersinggung jika teman membuat lelucon tentang saya di depan orang banyak.", bidang:"Sosial", sub_bidang:"Hubungan Teman", tipe:"Core", arah:"Negative" },
  { id:212, teks:"Saya bisa dengan mudah memaafkan teman yang tidak sengaja menyakiti perasaan saya.", bidang:"Sosial", sub_bidang:"Hubungan Teman", tipe:"Core", arah:"Positive" },
  { id:213, teks:"Saya merasa dikelilingi teman-teman yang benar-benar peduli dengan kondisi saya.", bidang:"Sosial", sub_bidang:"Hubungan Teman", tipe:"Core", arah:"Positive" },
  { id:214, teks:"Saya mampu langsung masuk mode fokus begitu duduk di meja belajar.", bidang:"Belajar", sub_bidang:"Fokus Belajar", tipe:"Core", arah:"Positive" },
  { id:215, teks:"Saya punya teknik khusus untuk menghalau distraksi saat sedang belajar penting.", bidang:"Belajar", sub_bidang:"Fokus Belajar", tipe:"Core", arah:"Positive" },
  { id:216, teks:"Saya bisa tetap konsentrasi belajar meskipun suasana sekitar agak ramai.", bidang:"Belajar", sub_bidang:"Fokus Belajar", tipe:"Core", arah:"Positive" },
  { id:217, teks:"Saya mampu tetap tenang menghadapi tekanan akademis tanpa kehilangan semangat.", bidang:"Belajar", sub_bidang:"Beban Belajar", tipe:"Core", arah:"Positive" },
  { id:218, teks:"Saya menerima proses belajar yang sulit sebagai bagian dari perjalanan menuju sukses.", bidang:"Belajar", sub_bidang:"Beban Belajar", tipe:"Core", arah:"Positive" },
  { id:219, teks:"Saya merasa aturan sekolah sering kali tidak adil dan tidak relevan untuk siswa.", bidang:"Belajar", sub_bidang:"Lingkungan Sekolah", tipe:"Core", arah:"Negative" },
  { id:220, teks:"Saya merasa hubungan saya dengan guru-guru di sekolah cukup baik dan saling menghormati.", bidang:"Belajar", sub_bidang:"Lingkungan Sekolah", tipe:"Core", arah:"Positive" },
];

// ── Metadata Sub Bidang (jumlah soal core per sub bidang) ──
const SUB_BIDANG_META = {
  // Pribadi
  "Gaya Hidup":       { bidang: "Pribadi",  count: 7,  ids: [9,16,28,30,35,44,45] },
  "Kematangan Emosi": { bidang: "Pribadi",  count: 11, ids: [2,13,14,20,22,27,33,34,37,47,50] },
  "Kesehatan Fisik":  { bidang: "Pribadi",  count: 9,  ids: [6,7,8,17,18,19,23,24,29] },
  "Kesehatan Mental": { bidang: "Pribadi",  count: 9,  ids: [1,10,11,12,21,36,43,48,49] },
  "Nilai & Moral":    { bidang: "Pribadi",  count: 5,  ids: [38,39,40,41,46] },
  // Belajar
  "Beban Belajar":          { bidang: "Belajar", count: 7, ids: [59,65,92,95,96,217,218] },
  "Fasilitas Belajar":      { bidang: "Belajar", count: 6, ids: [75,83,99,204,205,206] },
  "Fokus Belajar":          { bidang: "Belajar", count: 7, ids: [57,62,68,98,214,215,216] },
  "Keterampilan Belajar":   { bidang: "Belajar", count: 8, ids: [58,64,73,74,76,77,94,100] },
  "Lingkungan Sekolah":     { bidang: "Belajar", count: 6, ids: [63,67,79,86,219,220] },
  "Lingkungan Sosial Belajar": { bidang: "Belajar", count: 6, ids: [84,85,104,207,208,209] },
  "Manajemen Waktu":        { bidang: "Belajar", count: 5, ids: [55,56,78,89,105] },
  "Motivasi Belajar":       { bidang: "Belajar", count: 8, ids: [54,70,72,87,90,93,102,106] },
  "Sikap Belajar":          { bidang: "Belajar", count: 6, ids: [60,66,80,88,97,103] },
  // Sosial
  "Etika Sosial":           { bidang: "Sosial", count: 6,  ids: [114,129,132,137,143,149] },
  "Gaya Hidup & Lingkungan Sosial": { bidang: "Sosial", count: 8, ids: [116,127,198,199,200,201,202,203] },
  "Hubungan Keluarga":      { bidang: "Sosial", count: 8,  ids: [119,124,128,136,142,145,150,152] },
  "Hubungan Teman":         { bidang: "Sosial", count: 7,  ids: [110,112,153,210,211,212,213] },
  "Keterampilan Sosial":    { bidang: "Sosial", count: 9,  ids: [113,118,123,126,134,140,141,144,151] },
  "Masalah Sosial":         { bidang: "Sosial", count: 8,  ids: [115,117,122,133,135,138,146,147] },
  // Karir
  "Kesiapan Karir":         { bidang: "Karir", count: 7, ids: [158,161,164,171,176,179,195] },
  "Keterampilan Praktis":   { bidang: "Karir", count: 9, ids: [167,169,173,181,183,184,188,189,191] },
  "Minat & Bakat":          { bidang: "Karir", count: 11,ids: [156,160,163,170,174,178,182,185,192,194,197] },
  "Perencanaan Karir":      { bidang: "Karir", count: 7, ids: [159,162,175,177,186,190,193] },
};

// Consistency pairs mapping
const CONSISTENCY_PAIRS = [
  { pair: 1, neg: 26, pos: 3 },
  { pair: 2, neg: 31, pos: 4 },
  { pair: 3, neg: 52, pos: 69 },
  { pair: 4, neg: 82, pos: 53 },
  { pair: 5, neg: 107, pos: 121 },
  { pair: 6, neg: 108, pos: 125 },
  { pair: 7, neg: 109, pos: 131 },
  { pair: 8, neg: 154, pos: 166 },
  { pair: 9, neg: 155, pos: 168 },
];

// Lie scale IDs
const LIE_SCALE_IDS = [5,15,25,32,42,51,61,71,81,91,101,111,120,130,139,148,157,165,172,180,187,196];
